### ISSUE TITLE
Possibly depriacted code in go example causes go test fail in docker image

### ISSUE THREAD

**Issue by Nouri-Alnahawi** [vfarcic/go-demo-2#2]
While building the docker image directly inside the kluster (Chapter 8 Page 158) the following error message appears:

```

/go-demo-2 # docker image build -t vfarcic/go-demo-2:beta .
Sending build context to Docker daemon  106.5kB
Step 1/15 : FROM golang:1.9 AS build
 ---> ef89ef5c42a9
Step 2/15 : ADD . /src
 ---> Using cache
 ---> 65c29cf1b0b7
Step 3/15 : WORKDIR /src
 ---> Using cache
 ---> 99679df1b2ef
Step 4/15 : RUN go get -d -v -t
 ---> Using cache
 ---> ea45068d5f65
Step 5/15 : RUN go test --cover -v ./... --run UnitTest
 ---> Running in 68e693711e38
# _/src
/tmp/go-build021239558/_/src/_test/_obj_test/main.go:173:9: undefined: prometheus.Handler
FAIL	_/src [build failed]
The command '/bin/sh -c go test --cover -v ./... --run UnitTest' returned a non-zero code: 2
```

I have looked up the issue in Go forums, and maybe the library packages pulled during the build do not support this usage of Prometheus.

Cheers

**Comment by vfarcic** [comment]
Thank you for letting me know that there is an issue. It's been a while since I used that repository.

It should be fixed now. Can you please pull the latest code of go-demo-2 and try again?

**Comment by Nouri-Alnahawi** [comment]
Thank you for the quick fix. It's working now!
